package:
  name: fastaibreadcrumbs
  version: 0.0.8
source:
  sha256: 6507070f6b4c0fd8e16f8b6033106532dbf012d407d94b6c07bbfffe3b82b76a
  url: https://files.pythonhosted.org/packages/bc/36/22048a9be1c78a36eb785e71c92c9a5814da2e6ce63f121119ed40c1c7fe/fastaibreadcrumbs-0.0.8.tar.gz
about:
  dev_url: https://sapal6.github.io
  doc_url: https://sapal6.github.io
  home: https://sapal6.github.io
  license: Apache Software
  license_family: APACHE
  summary: Breadcrumbs for fastai users
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - sapal6
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - opencv-python
  - torchvision
  - fastkaggle
  run:
  - pip
  - python
  - packaging
  - fastai
  - opencv-python
  - torchvision
  - fastkaggle
test:
  imports:
  - fastaibreadcrumbs
