package:
  name: fastaibreadcrumbs
  version: 0.0.7
source:
  sha256: f8c5179cda842c0f5ee0f133e5ad4df540094e2bc2fc241108495ef0e531da80
  url: https://files.pythonhosted.org/packages/2a/03/a060839a1c9bab5e03ceadc66dc62f46ed0080b46bd808999ddcc57d1e06/fastaibreadcrumbs-0.0.7.tar.gz
about:
  dev_url: https://sapal6.github.io
  doc_url: https://sapal6.github.io
  home: https://sapal6.github.io
  license: Apache Software
  license_family: APACHE
  summary: Breadcrumbs for fastai users
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - sapal6
requirements:
  host:
  - pip
  - python
  - packaging
  - fastai
  - opencv-python
  - torchvision
  - fastkaggle
  run:
  - pip
  - python
  - packaging
  - fastai
  - opencv-python
  - torchvision
  - fastkaggle
test:
  imports:
  - fastaibreadcrumbs
